### ISSUE TITLE
your discord link don't work

### ISSUE THREAD

**Issue by Under-44** [NeonDevGit/HyDisc#1]
![image](https://user-images.githubusercontent.com/69401550/181686096-13426162-5ff6-4bde-a11a-1d9c268cc39d.png)

cool project, best of luck.

**Comment by NeonDevGit** [comment]
Thanks, I will look into that today

**Comment by NeonDevGit** [comment]
Fixed it should work now, if not here https://discord.gg/9Q7SBStDef
